### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by alphafox02** [krono-i2/gr-spoof1090#1]
On 22.04.2 w/ GNU Radio 3.10.4 I'm getting the following when running the example test flow graph. 

Traceback (most recent call last):
  File "/home/test/Downloads/gr-spoof1090/examples/test.py", line 34, in <module>
    from gnuradio import spoof1090
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/spoof1090/__init__.py", line 18, in <module>
    from .spoof1090_python import *
ImportError: /usr/local/lib/libgnuradio-spoof1090.so.1.0.0: undefined symbol: _ZN2gr9spoof109019adsb_mod_async_impl4workEiRSt6vectorIPKvSaIS4_EERS2_IPvSaIS8_EE

**Comment by krono-i2** [comment]
Maybe you need to reload shared library after install.
`sudo ldconfig`

**Comment by alphafox02** [comment]
Forgot to mention I did that. The encoder works, and if I disable the adsb middle block in the flow graph and go direct from zmq to the print block it runs.

**Comment by alphafox02** [comment]
With 22.04.2, are you using just the stock apt provided gnuradio? No ppa or source install, right? I’ll setup the same thing as you and try again. Right now I have a source install of 3.10.4.

**Comment by alphafox02** [comment]
I took a stock 22.04.2 Lubuntu install (gnuradio 3.10.1), then installed only the dependencies needed to build this project. After installing and after sudo ldconfig, same exact symbol missing issue.

**Comment by krono-i2** [comment]
I have just encountered the same issue on a brand new virtual machine.
I will study what is going on.

**Comment by krono-i2** [comment]
The commit 42ee7764e84ca2a03ed78eda8072972af144191d resolved this issue.

**Comment by alphafox02** [comment]
Works now on this end too, thank you!
